apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otel-demo-app
  template:
    metadata:
      labels:
        app: otel-demo-app
    spec:
      containers:
      - name: otel-demo-app
        image: 954692414134.dkr.ecr.ap-south-1.amazonaws.com/otel-demo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-demo-app
spec:
  type: NodePort
  selector:
    app: otel-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
