# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318

# processors:
#   memory_limiter:
#     check_interval: 1s
#     limit_mib: 512
#   batch:
#   # resource:
#     attributes:
#       - key: service.environment
#         value: production
#         action: upsert

# exporters:
#   jaeger:
#     endpoint: http://jaeger:14268/api/traces
#     tls:
#       insecure: true

#   loki:
#     endpoint: http://loki:3100/loki/api/v1/push

#   prometheus:
#     endpoint: 0.0.0.0:8889

#   logging:
#     verbosity: normal

# extensions:
#   health_check:
#     endpoint: 0.0.0.0:13133

# service:
#   extensions: [health_check]
#   pipelines:
#     traces:
#       receivers: [otlp]
#       processors: [memory_limiter, batch, resource]
#       exporters: [jaeger, logging]

#     metrics:
#       receivers: [otlp]
#       processors: [memory_limiter, batch, resource]
#       exporters: [prometheus, logging]

#     logs:
#       receivers: [otlp]
#       processors: [memory_limiter, batch, resource]
#       exporters: [loki, logging]
